#
# docker build --network=host \
#               --tag=stonesteps/webalizer-fedora:latest \
#               --file=/path/to/Dockerfile.fedora \
#                   /path/to/context
#
FROM fedora

#
# Dependencies
#
RUN dnf install -y gcc-c++ make libdb-cxx-devel zlib libmaxminddb-devel gd-devel gtest-devel
